#!/usr/bin/env php
<?php
if (PHP_VERSION_ID < 80100) {
    die('Sonic only works with PHP >=8.1');
}

define('SONIC', __DIR__);
define('APP', SONIC . '/app');
define('CORE', SONIC . '/core');
require CORE . '/bootstrap.php';

(new \Sonic\Sonic())->console();