#!/usr/bin/env php
<?php
if (PHP_MAJOR_VERSION < 8) {
    die('Sonic only works with PHP >=8.0');
}

define('SONIC', __DIR__);
define('APP', SONIC . '/app');
define('CORE', SONIC . '/core');
require CORE . '/bootstrap.php';

(new \Sonic\Sonic())->console();